# Generates the weight tables in Assets/Scripts/Core/TileDealer.cs from
# jamo frequencies in Assets/Resources/topik1_words.json.
#
#   powershell -ExecutionPolicy Bypass -File Tools\gen_jamo_weights.ps1
#
# Method:
#  - Every word is decomposed into cho/jung/jong jamo (same Unicode
#    arithmetic as HangulComposer).
#  - Consonant demand counts BOTH initial (choseong) and final (jongseong)
#    occurrences, because one consonant tile serves either position.
#    Compound jongseong (e.g. U+3133, U+3135) are never dealt as random
#    tiles, so they are excluded here.
#  - Raw frequencies are damped with x^0.7 so very common jamo do not
#    flood the tray with duplicates; results are rounded to integers
#    (minimum 1 for any jamo that occurs at all; 0 if absent from corpus).
#
# The script is ASCII-only; jamo characters are built from code points so
# file encoding can never corrupt the tables.

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

function J([int]$code) { [string][char]$code }

# Compatibility-jamo code points, in the same order as HangulComposer's tables.
$choCodes  = 0x3131,0x3132,0x3134,0x3137,0x3138,0x3139,0x3141,0x3142,0x3143,
             0x3145,0x3146,0x3147,0x3148,0x3149,0x314A,0x314B,0x314C,0x314D,0x314E
$jungCodes = 0x314F..0x3163
$jongCodes = 0,0x3131,0x3132,0x3133,0x3134,0x3135,0x3136,0x3137,0x3139,
             0x313A,0x313B,0x313C,0x313D,0x313E,0x313F,0x3140,0x3141,0x3142,
             0x3144,0x3145,0x3146,0x3147,0x3148,0x314A,0x314B,0x314C,0x314D,0x314E

$cho  = @($choCodes  | ForEach-Object { J $_ })
$jung = @($jungCodes | ForEach-Object { J $_ })
$jong = @($jongCodes | ForEach-Object { if ($_ -eq 0) { '' } else { J $_ } })

$root = Split-Path -Parent $PSScriptRoot
$json = Get-Content -Raw -Encoding UTF8 (Join-Path $root 'Assets\Resources\topik1_words.json') | ConvertFrom-Json

$consonant = @{}; $vowel = @{}
foreach ($k in $cho)  { $consonant[$k] = 0 }
foreach ($k in $jung) { $vowel[$k] = 0 }
$totalSyllables = 0

foreach ($w in $json.words) {
    foreach ($ch in $w.word.ToCharArray()) {
        $code = [int]$ch
        if ($code -lt 0xAC00 -or $code -gt 0xD7A3) { continue }
        $off = $code - 0xAC00
        $totalSyllables++
        $consonant[$cho[[math]::Floor($off / 588)]]++
        $vowel[$jung[[math]::Floor(($off % 588) / 28)]]++
        $f = $jong[$off % 28]
        # Single-consonant finals feed the same tile pool as initials;
        # compound finals are not dealt as random tiles.
        if ($f -ne '' -and $consonant.ContainsKey($f)) { $consonant[$f]++ }
    }
}

function Emit-Table([string]$name, [string[]]$order, [hashtable]$counts) {
    $damped = @{}
    foreach ($k in $order) {
        if ($counts[$k] -eq 0) { $damped[$k] = 0 }
        else { $damped[$k] = [math]::Max(1, [int][math]::Round([math]::Pow($counts[$k], 0.7))) }
    }
    Write-Output "    private static readonly (string jamo, int weight)[] $name ="
    Write-Output "    {"
    for ($i = 0; $i -lt $order.Count; $i += 5) {
        $chunk = $order[$i..([math]::Min($i + 4, $order.Count - 1))]
        $line = '        ' + (($chunk | ForEach-Object { '("' + $_ + '", ' + $damped[$_] + ')' }) -join ', ') + ','
        Write-Output $line
    }
    Write-Output "    };"
    $total = ($order | ForEach-Object { $damped[$_] } | Measure-Object -Sum).Sum
    $countTotal = ($order | ForEach-Object { $counts[$_] } | Measure-Object -Sum).Sum
    Write-Output "    // check: $($order.Count) jamo, weight sum $total"
    foreach ($k in ($order | Sort-Object { -$counts[$_] })) {
        $pct  = if ($countTotal -gt 0) { 100 * $counts[$k] / $countTotal } else { 0 }
        $wpct = if ($total -gt 0) { 100 * $damped[$k] / $total } else { 0 }
        Write-Output ("    //   {0}  corpus {1,4} ({2,5:N2}%)  weight {3,3} -> dealt {4,5:N2}%" -f $k, $counts[$k], $pct, $damped[$k], $wpct)
    }
}

Write-Output "// Generated by Tools/gen_jamo_weights.ps1 from topik1_words.json"
Write-Output "// ($($json.words.Count) words, $totalSyllables syllables). Do not hand-edit; re-run the script."
Emit-Table 'ChoseongWeights' $cho $consonant
Write-Output ""
Emit-Table 'JungseongWeights' $jung $vowel
