using System.Collections.Generic;

// Pure logic (no UnityEngine) so it can be unit tested and, later,
// seeded deterministically for the Phase 4 daily puzzle.
public class TileDealer
{
    // Weights derived from actual jamo frequency in topik1_words.json
    // (894 words, 2050 syllables), damped with x^0.7 so common jamo lead
    // without flooding the tray with duplicates. Consonant weights count
    // both initial (choseong) and final (jongseong) occurrences, since
    // one consonant tile serves either position. ㅞ never occurs in the
    // corpus and is not dealt. Generated by Tools/gen_jamo_weights.ps1 —
    // re-run it instead of hand-editing when the word list changes.
    private static readonly (string jamo, int weight)[] ChoseongWeights =
    {
        ("ㄱ", 61), ("ㄲ", 8), ("ㄴ", 54), ("ㄷ", 58), ("ㄸ", 8),
        ("ㄹ", 51), ("ㅁ", 40), ("ㅂ", 33), ("ㅃ", 5), ("ㅅ", 47),
        ("ㅆ", 7), ("ㅇ", 74), ("ㅈ", 36), ("ㅉ", 8), ("ㅊ", 18),
        ("ㅋ", 8), ("ㅌ", 12), ("ㅍ", 13), ("ㅎ", 35)
    };

    private static readonly (string jamo, int weight)[] JungseongWeights =
    {
        ("ㅏ", 98), ("ㅐ", 26), ("ㅑ", 6), ("ㅒ", 2), ("ㅓ", 41),
        ("ㅔ", 13), ("ㅕ", 21), ("ㅖ", 6), ("ㅗ", 39), ("ㅘ", 9),
        ("ㅙ", 3), ("ㅚ", 6), ("ㅛ", 11), ("ㅜ", 36), ("ㅝ", 9),
        ("ㅞ", 0), ("ㅟ", 5), ("ㅠ", 6), ("ㅡ", 31), ("ㅢ", 3),
        ("ㅣ", 53)
    };

    // Fraction of dealt tiles that are consonants; the rest are vowels.
    // Corpus tile demand is 58.6% consonants — for the 14-tile tray both
    // ratios give the same 8/6 split, so keep the rounder number.
    private const double ConsonantRatio = 0.55;

    private readonly System.Random _random;

    public TileDealer() : this(System.Environment.TickCount) { }

    public TileDealer(int seed)
    {
        _random = new System.Random(seed);
    }

    public string NextChoseong() => WeightedPick(ChoseongWeights);

    public string NextJungseong() => WeightedPick(JungseongWeights);

    public string NextJamo() =>
        _random.NextDouble() < ConsonantRatio ? NextChoseong() : NextJungseong();

    // Exposes the dealer's RNG so tray shuffles stay deterministic under
    // a seed (Phase 4 daily puzzle).
    public int NextIndex(int maxExclusive) => _random.Next(maxExclusive);

    // Deals a balanced hand: ~55% consonants, ~45% vowels, shuffled,
    // so a full tray always contains enough vowels to build syllables.
    public List<string> Deal(int count)
    {
        int consonants = (int)System.Math.Round(count * ConsonantRatio);
        var result = new List<string>(count);

        for (int i = 0; i < consonants && i < count; i++)
            result.Add(NextChoseong());
        while (result.Count < count)
            result.Add(NextJungseong());

        Shuffle(result);
        return result;
    }

    private void Shuffle(List<string> list)
    {
        for (int i = list.Count - 1; i > 0; i--)
        {
            int j = _random.Next(i + 1);
            (list[i], list[j]) = (list[j], list[i]);
        }
    }

    private string WeightedPick((string jamo, int weight)[] pool)
    {
        int total = 0;
        foreach (var entry in pool)
            total += entry.weight;

        int roll = _random.Next(total);
        foreach (var entry in pool)
        {
            roll -= entry.weight;
            if (roll < 0) return entry.jamo;
        }
        return pool[pool.Length - 1].jamo;
    }
}
